version: "3.9"

services:
  web:
    build: .
    image: etherium/antennas:latest
    container_name: antennas-web
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      DATABASE_URL: "file:/app/prisma/data/db.sqlite" # persiste no volume
      NODE_ENV: "production"
      PORT: "3000"
      NEXT_TELEMETRY_DISABLED: "1"
      # GDMS_BASE: "https://www.gwn.cloud"   # (opcional) sobrescreva se precisar
    volumes:
      - sqlite-data:/app/prisma/data
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:3000/api/health || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 5

  worker:
    image: etherium/antennas:latest
    container_name: antennas-worker
    restart: unless-stopped
    depends_on:
      web:
        condition: service_healthy
    env_file:
      - .env
    environment:
      APP_BASE_URL: "http://web:3000"           # chama o endpoint do web
      SYNC_INTERVAL_MS: "300000"                # 5 minutos
      SYNC_PATH: "/api/integrations/gdms/sync"  # endpoint de sync
      DATABASE_URL: "file:/app/prisma/data/db.sqlite"
      NODE_ENV: "production"
    command: ["node", "scripts/gdms-cron.mjs"]
    volumes:
      - sqlite-data:/app/prisma/data

volumes:
  sqlite-data:
